//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transactions_Automation.HAAD_WS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.shafafiya.org/v2/", ConfigurationName="HAAD_WS.WebservicesSoap")]
    public interface WebservicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/UploadTransaction", ReplyAction="*")]
        Transactions_Automation.HAAD_WS.UploadTransactionResponse UploadTransaction(Transactions_Automation.HAAD_WS.UploadTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/UploadTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<Transactions_Automation.HAAD_WS.UploadTransactionResponse> UploadTransactionAsync(Transactions_Automation.HAAD_WS.UploadTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/GetNewTransactions", ReplyAction="*")]
        Transactions_Automation.HAAD_WS.GetNewTransactionsResponse GetNewTransactions(Transactions_Automation.HAAD_WS.GetNewTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/GetNewTransactions", ReplyAction="*")]
        System.Threading.Tasks.Task<Transactions_Automation.HAAD_WS.GetNewTransactionsResponse> GetNewTransactionsAsync(Transactions_Automation.HAAD_WS.GetNewTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/DownloadTransactionFile", ReplyAction="*")]
        Transactions_Automation.HAAD_WS.DownloadTransactionFileResponse DownloadTransactionFile(Transactions_Automation.HAAD_WS.DownloadTransactionFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/DownloadTransactionFile", ReplyAction="*")]
        System.Threading.Tasks.Task<Transactions_Automation.HAAD_WS.DownloadTransactionFileResponse> DownloadTransactionFileAsync(Transactions_Automation.HAAD_WS.DownloadTransactionFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/SearchTransactions", ReplyAction="*")]
        Transactions_Automation.HAAD_WS.SearchTransactionsResponse SearchTransactions(Transactions_Automation.HAAD_WS.SearchTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/SearchTransactions", ReplyAction="*")]
        System.Threading.Tasks.Task<Transactions_Automation.HAAD_WS.SearchTransactionsResponse> SearchTransactionsAsync(Transactions_Automation.HAAD_WS.SearchTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/SetTransactionDownloaded", ReplyAction="*")]
        Transactions_Automation.HAAD_WS.SetTransactionDownloadedResponse SetTransactionDownloaded(Transactions_Automation.HAAD_WS.SetTransactionDownloadedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/SetTransactionDownloaded", ReplyAction="*")]
        System.Threading.Tasks.Task<Transactions_Automation.HAAD_WS.SetTransactionDownloadedResponse> SetTransactionDownloadedAsync(Transactions_Automation.HAAD_WS.SetTransactionDownloadedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/GetPrescriptions", ReplyAction="*")]
        Transactions_Automation.HAAD_WS.GetPrescriptionsResponse GetPrescriptions(Transactions_Automation.HAAD_WS.GetPrescriptionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/GetPrescriptions", ReplyAction="*")]
        System.Threading.Tasks.Task<Transactions_Automation.HAAD_WS.GetPrescriptionsResponse> GetPrescriptionsAsync(Transactions_Automation.HAAD_WS.GetPrescriptionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/AddDRGToEClaim", ReplyAction="*")]
        Transactions_Automation.HAAD_WS.AddDRGToEClaimResponse AddDRGToEClaim(Transactions_Automation.HAAD_WS.AddDRGToEClaimRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/AddDRGToEClaim", ReplyAction="*")]
        System.Threading.Tasks.Task<Transactions_Automation.HAAD_WS.AddDRGToEClaimResponse> AddDRGToEClaimAsync(Transactions_Automation.HAAD_WS.AddDRGToEClaimRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/CheckForNewPriorAuthorizationTransactions", ReplyAction="*")]
        Transactions_Automation.HAAD_WS.CheckForNewPriorAuthorizationTransactionsResponse CheckForNewPriorAuthorizationTransactions(Transactions_Automation.HAAD_WS.CheckForNewPriorAuthorizationTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/CheckForNewPriorAuthorizationTransactions", ReplyAction="*")]
        System.Threading.Tasks.Task<Transactions_Automation.HAAD_WS.CheckForNewPriorAuthorizationTransactionsResponse> CheckForNewPriorAuthorizationTransactionsAsync(Transactions_Automation.HAAD_WS.CheckForNewPriorAuthorizationTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/GetNewPriorAuthorizationTransactions", ReplyAction="*")]
        Transactions_Automation.HAAD_WS.GetNewPriorAuthorizationTransactionsResponse GetNewPriorAuthorizationTransactions(Transactions_Automation.HAAD_WS.GetNewPriorAuthorizationTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/GetNewPriorAuthorizationTransactions", ReplyAction="*")]
        System.Threading.Tasks.Task<Transactions_Automation.HAAD_WS.GetNewPriorAuthorizationTransactionsResponse> GetNewPriorAuthorizationTransactionsAsync(Transactions_Automation.HAAD_WS.GetNewPriorAuthorizationTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/GetDRGDetails", ReplyAction="*")]
        Transactions_Automation.HAAD_WS.GetDRGDetailsResponse GetDRGDetails(Transactions_Automation.HAAD_WS.GetDRGDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/GetDRGDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<Transactions_Automation.HAAD_WS.GetDRGDetailsResponse> GetDRGDetailsAsync(Transactions_Automation.HAAD_WS.GetDRGDetailsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadTransaction", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public Transactions_Automation.HAAD_WS.UploadTransactionRequestBody Body;
        
        public UploadTransactionRequest() {
        }
        
        public UploadTransactionRequest(Transactions_Automation.HAAD_WS.UploadTransactionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class UploadTransactionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] fileContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string fileName;
        
        public UploadTransactionRequestBody() {
        }
        
        public UploadTransactionRequestBody(string login, string pwd, byte[] fileContent, string fileName) {
            this.login = login;
            this.pwd = pwd;
            this.fileContent = fileContent;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadTransactionResponse", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public Transactions_Automation.HAAD_WS.UploadTransactionResponseBody Body;
        
        public UploadTransactionResponse() {
        }
        
        public UploadTransactionResponse(Transactions_Automation.HAAD_WS.UploadTransactionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class UploadTransactionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UploadTransactionResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string errorMessage;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] errorReport;
        
        public UploadTransactionResponseBody() {
        }
        
        public UploadTransactionResponseBody(int UploadTransactionResult, string errorMessage, byte[] errorReport) {
            this.UploadTransactionResult = UploadTransactionResult;
            this.errorMessage = errorMessage;
            this.errorReport = errorReport;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewTransactionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewTransactions", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public Transactions_Automation.HAAD_WS.GetNewTransactionsRequestBody Body;
        
        public GetNewTransactionsRequest() {
        }
        
        public GetNewTransactionsRequest(Transactions_Automation.HAAD_WS.GetNewTransactionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class GetNewTransactionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        public GetNewTransactionsRequestBody() {
        }
        
        public GetNewTransactionsRequestBody(string login, string pwd) {
            this.login = login;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewTransactionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewTransactionsResponse", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public Transactions_Automation.HAAD_WS.GetNewTransactionsResponseBody Body;
        
        public GetNewTransactionsResponse() {
        }
        
        public GetNewTransactionsResponse(Transactions_Automation.HAAD_WS.GetNewTransactionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class GetNewTransactionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetNewTransactionsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xmlTransactions;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string errorMessage;
        
        public GetNewTransactionsResponseBody() {
        }
        
        public GetNewTransactionsResponseBody(int GetNewTransactionsResult, string xmlTransactions, string errorMessage) {
            this.GetNewTransactionsResult = GetNewTransactionsResult;
            this.xmlTransactions = xmlTransactions;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadTransactionFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadTransactionFile", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public Transactions_Automation.HAAD_WS.DownloadTransactionFileRequestBody Body;
        
        public DownloadTransactionFileRequest() {
        }
        
        public DownloadTransactionFileRequest(Transactions_Automation.HAAD_WS.DownloadTransactionFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class DownloadTransactionFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fileId;
        
        public DownloadTransactionFileRequestBody() {
        }
        
        public DownloadTransactionFileRequestBody(string login, string pwd, string fileId) {
            this.login = login;
            this.pwd = pwd;
            this.fileId = fileId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadTransactionFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadTransactionFileResponse", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public Transactions_Automation.HAAD_WS.DownloadTransactionFileResponseBody Body;
        
        public DownloadTransactionFileResponse() {
        }
        
        public DownloadTransactionFileResponse(Transactions_Automation.HAAD_WS.DownloadTransactionFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class DownloadTransactionFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DownloadTransactionFileResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] file;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string errorMessage;
        
        public DownloadTransactionFileResponseBody() {
        }
        
        public DownloadTransactionFileResponseBody(int DownloadTransactionFileResult, string fileName, byte[] file, string errorMessage) {
            this.DownloadTransactionFileResult = DownloadTransactionFileResult;
            this.fileName = fileName;
            this.file = file;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchTransactionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchTransactions", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public Transactions_Automation.HAAD_WS.SearchTransactionsRequestBody Body;
        
        public SearchTransactionsRequest() {
        }
        
        public SearchTransactionsRequest(Transactions_Automation.HAAD_WS.SearchTransactionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class SearchTransactionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int direction;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string callerLicense;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ePartner;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int transactionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int transactionStatus;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string transactionFileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string transactionFromDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string transactionToDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int minRecordCount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public int maxRecordCount;
        
        public SearchTransactionsRequestBody() {
        }
        
        public SearchTransactionsRequestBody(string login, string pwd, int direction, string callerLicense, string ePartner, int transactionID, int transactionStatus, string transactionFileName, string transactionFromDate, string transactionToDate, int minRecordCount, int maxRecordCount) {
            this.login = login;
            this.pwd = pwd;
            this.direction = direction;
            this.callerLicense = callerLicense;
            this.ePartner = ePartner;
            this.transactionID = transactionID;
            this.transactionStatus = transactionStatus;
            this.transactionFileName = transactionFileName;
            this.transactionFromDate = transactionFromDate;
            this.transactionToDate = transactionToDate;
            this.minRecordCount = minRecordCount;
            this.maxRecordCount = maxRecordCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchTransactionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchTransactionsResponse", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public Transactions_Automation.HAAD_WS.SearchTransactionsResponseBody Body;
        
        public SearchTransactionsResponse() {
        }
        
        public SearchTransactionsResponse(Transactions_Automation.HAAD_WS.SearchTransactionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class SearchTransactionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SearchTransactionsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string foundTransactions;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string errorMessage;
        
        public SearchTransactionsResponseBody() {
        }
        
        public SearchTransactionsResponseBody(int SearchTransactionsResult, string foundTransactions, string errorMessage) {
            this.SearchTransactionsResult = SearchTransactionsResult;
            this.foundTransactions = foundTransactions;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetTransactionDownloadedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetTransactionDownloaded", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public Transactions_Automation.HAAD_WS.SetTransactionDownloadedRequestBody Body;
        
        public SetTransactionDownloadedRequest() {
        }
        
        public SetTransactionDownloadedRequest(Transactions_Automation.HAAD_WS.SetTransactionDownloadedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class SetTransactionDownloadedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fileId;
        
        public SetTransactionDownloadedRequestBody() {
        }
        
        public SetTransactionDownloadedRequestBody(string login, string pwd, string fileId) {
            this.login = login;
            this.pwd = pwd;
            this.fileId = fileId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetTransactionDownloadedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetTransactionDownloadedResponse", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public Transactions_Automation.HAAD_WS.SetTransactionDownloadedResponseBody Body;
        
        public SetTransactionDownloadedResponse() {
        }
        
        public SetTransactionDownloadedResponse(Transactions_Automation.HAAD_WS.SetTransactionDownloadedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class SetTransactionDownloadedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SetTransactionDownloadedResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string errorMessage;
        
        public SetTransactionDownloadedResponseBody() {
        }
        
        public SetTransactionDownloadedResponseBody(int SetTransactionDownloadedResult, string errorMessage) {
            this.SetTransactionDownloadedResult = SetTransactionDownloadedResult;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPrescriptionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPrescriptions", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public Transactions_Automation.HAAD_WS.GetPrescriptionsRequestBody Body;
        
        public GetPrescriptionsRequest() {
        }
        
        public GetPrescriptionsRequest(Transactions_Automation.HAAD_WS.GetPrescriptionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class GetPrescriptionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string payerID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string memberID;
        
        public GetPrescriptionsRequestBody() {
        }
        
        public GetPrescriptionsRequestBody(string login, string pwd, string payerID, string memberID) {
            this.login = login;
            this.pwd = pwd;
            this.payerID = payerID;
            this.memberID = memberID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPrescriptionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPrescriptionsResponse", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public Transactions_Automation.HAAD_WS.GetPrescriptionsResponseBody Body;
        
        public GetPrescriptionsResponse() {
        }
        
        public GetPrescriptionsResponse(Transactions_Automation.HAAD_WS.GetPrescriptionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class GetPrescriptionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetPrescriptionsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] prescription;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string errorMessage;
        
        public GetPrescriptionsResponseBody() {
        }
        
        public GetPrescriptionsResponseBody(int GetPrescriptionsResult, byte[] prescription, string errorMessage) {
            this.GetPrescriptionsResult = GetPrescriptionsResult;
            this.prescription = prescription;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDRGToEClaimRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDRGToEClaim", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public Transactions_Automation.HAAD_WS.AddDRGToEClaimRequestBody Body;
        
        public AddDRGToEClaimRequest() {
        }
        
        public AddDRGToEClaimRequest(Transactions_Automation.HAAD_WS.AddDRGToEClaimRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class AddDRGToEClaimRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] originalFileContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string originalFileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal baseRate;
        
        public AddDRGToEClaimRequestBody() {
        }
        
        public AddDRGToEClaimRequestBody(string login, string pwd, byte[] originalFileContent, string originalFileName, decimal baseRate) {
            this.login = login;
            this.pwd = pwd;
            this.originalFileContent = originalFileContent;
            this.originalFileName = originalFileName;
            this.baseRate = baseRate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDRGToEClaimResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDRGToEClaimResponse", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public Transactions_Automation.HAAD_WS.AddDRGToEClaimResponseBody Body;
        
        public AddDRGToEClaimResponse() {
        }
        
        public AddDRGToEClaimResponse(Transactions_Automation.HAAD_WS.AddDRGToEClaimResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class AddDRGToEClaimResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddDRGToEClaimResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] drgFileContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string drgFileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] auditFileContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public byte[] reportFileContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string errorMessage;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public byte[] errorReport;
        
        public AddDRGToEClaimResponseBody() {
        }
        
        public AddDRGToEClaimResponseBody(int AddDRGToEClaimResult, byte[] drgFileContent, string drgFileName, byte[] auditFileContent, byte[] reportFileContent, string errorMessage, byte[] errorReport) {
            this.AddDRGToEClaimResult = AddDRGToEClaimResult;
            this.drgFileContent = drgFileContent;
            this.drgFileName = drgFileName;
            this.auditFileContent = auditFileContent;
            this.reportFileContent = reportFileContent;
            this.errorMessage = errorMessage;
            this.errorReport = errorReport;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckForNewPriorAuthorizationTransactionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckForNewPriorAuthorizationTransactions", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public Transactions_Automation.HAAD_WS.CheckForNewPriorAuthorizationTransactionsRequestBody Body;
        
        public CheckForNewPriorAuthorizationTransactionsRequest() {
        }
        
        public CheckForNewPriorAuthorizationTransactionsRequest(Transactions_Automation.HAAD_WS.CheckForNewPriorAuthorizationTransactionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class CheckForNewPriorAuthorizationTransactionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        public CheckForNewPriorAuthorizationTransactionsRequestBody() {
        }
        
        public CheckForNewPriorAuthorizationTransactionsRequestBody(string login, string pwd) {
            this.login = login;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckForNewPriorAuthorizationTransactionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckForNewPriorAuthorizationTransactionsResponse", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public Transactions_Automation.HAAD_WS.CheckForNewPriorAuthorizationTransactionsResponseBody Body;
        
        public CheckForNewPriorAuthorizationTransactionsResponse() {
        }
        
        public CheckForNewPriorAuthorizationTransactionsResponse(Transactions_Automation.HAAD_WS.CheckForNewPriorAuthorizationTransactionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class CheckForNewPriorAuthorizationTransactionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CheckForNewPriorAuthorizationTransactionsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string errorMessage;
        
        public CheckForNewPriorAuthorizationTransactionsResponseBody() {
        }
        
        public CheckForNewPriorAuthorizationTransactionsResponseBody(int CheckForNewPriorAuthorizationTransactionsResult, string errorMessage) {
            this.CheckForNewPriorAuthorizationTransactionsResult = CheckForNewPriorAuthorizationTransactionsResult;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewPriorAuthorizationTransactionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewPriorAuthorizationTransactions", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public Transactions_Automation.HAAD_WS.GetNewPriorAuthorizationTransactionsRequestBody Body;
        
        public GetNewPriorAuthorizationTransactionsRequest() {
        }
        
        public GetNewPriorAuthorizationTransactionsRequest(Transactions_Automation.HAAD_WS.GetNewPriorAuthorizationTransactionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class GetNewPriorAuthorizationTransactionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        public GetNewPriorAuthorizationTransactionsRequestBody() {
        }
        
        public GetNewPriorAuthorizationTransactionsRequestBody(string login, string pwd) {
            this.login = login;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewPriorAuthorizationTransactionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewPriorAuthorizationTransactionsResponse", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public Transactions_Automation.HAAD_WS.GetNewPriorAuthorizationTransactionsResponseBody Body;
        
        public GetNewPriorAuthorizationTransactionsResponse() {
        }
        
        public GetNewPriorAuthorizationTransactionsResponse(Transactions_Automation.HAAD_WS.GetNewPriorAuthorizationTransactionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class GetNewPriorAuthorizationTransactionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetNewPriorAuthorizationTransactionsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string foundTransactions;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string errorMessage;
        
        public GetNewPriorAuthorizationTransactionsResponseBody() {
        }
        
        public GetNewPriorAuthorizationTransactionsResponseBody(int GetNewPriorAuthorizationTransactionsResult, string foundTransactions, string errorMessage) {
            this.GetNewPriorAuthorizationTransactionsResult = GetNewPriorAuthorizationTransactionsResult;
            this.foundTransactions = foundTransactions;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDRGDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDRGDetails", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public Transactions_Automation.HAAD_WS.GetDRGDetailsRequestBody Body;
        
        public GetDRGDetailsRequest() {
        }
        
        public GetDRGDetailsRequest(Transactions_Automation.HAAD_WS.GetDRGDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class GetDRGDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string xmlClaimInput;
        
        public GetDRGDetailsRequestBody() {
        }
        
        public GetDRGDetailsRequestBody(string login, string pwd, string xmlClaimInput) {
            this.login = login;
            this.pwd = pwd;
            this.xmlClaimInput = xmlClaimInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDRGDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDRGDetailsResponse", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public Transactions_Automation.HAAD_WS.GetDRGDetailsResponseBody Body;
        
        public GetDRGDetailsResponse() {
        }
        
        public GetDRGDetailsResponse(Transactions_Automation.HAAD_WS.GetDRGDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class GetDRGDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetDRGDetailsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xmlDRGDetails;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] auditFileContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] reportFileContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string errorMessage;
        
        public GetDRGDetailsResponseBody() {
        }
        
        public GetDRGDetailsResponseBody(int GetDRGDetailsResult, string xmlDRGDetails, byte[] auditFileContent, byte[] reportFileContent, string errorMessage) {
            this.GetDRGDetailsResult = GetDRGDetailsResult;
            this.xmlDRGDetails = xmlDRGDetails;
            this.auditFileContent = auditFileContent;
            this.reportFileContent = reportFileContent;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebservicesSoapChannel : Transactions_Automation.HAAD_WS.WebservicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebservicesSoapClient : System.ServiceModel.ClientBase<Transactions_Automation.HAAD_WS.WebservicesSoap>, Transactions_Automation.HAAD_WS.WebservicesSoap {
        
        public WebservicesSoapClient() {
        }
        
        public WebservicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebservicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebservicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebservicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Transactions_Automation.HAAD_WS.UploadTransactionResponse Transactions_Automation.HAAD_WS.WebservicesSoap.UploadTransaction(Transactions_Automation.HAAD_WS.UploadTransactionRequest request) {
            return base.Channel.UploadTransaction(request);
        }
        
        public int UploadTransaction(string login, string pwd, byte[] fileContent, string fileName, out string errorMessage, out byte[] errorReport) {
            Transactions_Automation.HAAD_WS.UploadTransactionRequest inValue = new Transactions_Automation.HAAD_WS.UploadTransactionRequest();
            inValue.Body = new Transactions_Automation.HAAD_WS.UploadTransactionRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.fileContent = fileContent;
            inValue.Body.fileName = fileName;
            Transactions_Automation.HAAD_WS.UploadTransactionResponse retVal = ((Transactions_Automation.HAAD_WS.WebservicesSoap)(this)).UploadTransaction(inValue);
            errorMessage = retVal.Body.errorMessage;
            errorReport = retVal.Body.errorReport;
            return retVal.Body.UploadTransactionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Transactions_Automation.HAAD_WS.UploadTransactionResponse> Transactions_Automation.HAAD_WS.WebservicesSoap.UploadTransactionAsync(Transactions_Automation.HAAD_WS.UploadTransactionRequest request) {
            return base.Channel.UploadTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Transactions_Automation.HAAD_WS.UploadTransactionResponse> UploadTransactionAsync(string login, string pwd, byte[] fileContent, string fileName) {
            Transactions_Automation.HAAD_WS.UploadTransactionRequest inValue = new Transactions_Automation.HAAD_WS.UploadTransactionRequest();
            inValue.Body = new Transactions_Automation.HAAD_WS.UploadTransactionRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.fileContent = fileContent;
            inValue.Body.fileName = fileName;
            return ((Transactions_Automation.HAAD_WS.WebservicesSoap)(this)).UploadTransactionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Transactions_Automation.HAAD_WS.GetNewTransactionsResponse Transactions_Automation.HAAD_WS.WebservicesSoap.GetNewTransactions(Transactions_Automation.HAAD_WS.GetNewTransactionsRequest request) {
            return base.Channel.GetNewTransactions(request);
        }
        
        public int GetNewTransactions(string login, string pwd, out string xmlTransactions, out string errorMessage) {
            Transactions_Automation.HAAD_WS.GetNewTransactionsRequest inValue = new Transactions_Automation.HAAD_WS.GetNewTransactionsRequest();
            inValue.Body = new Transactions_Automation.HAAD_WS.GetNewTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            Transactions_Automation.HAAD_WS.GetNewTransactionsResponse retVal = ((Transactions_Automation.HAAD_WS.WebservicesSoap)(this)).GetNewTransactions(inValue);
            xmlTransactions = retVal.Body.xmlTransactions;
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.GetNewTransactionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Transactions_Automation.HAAD_WS.GetNewTransactionsResponse> Transactions_Automation.HAAD_WS.WebservicesSoap.GetNewTransactionsAsync(Transactions_Automation.HAAD_WS.GetNewTransactionsRequest request) {
            return base.Channel.GetNewTransactionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Transactions_Automation.HAAD_WS.GetNewTransactionsResponse> GetNewTransactionsAsync(string login, string pwd) {
            Transactions_Automation.HAAD_WS.GetNewTransactionsRequest inValue = new Transactions_Automation.HAAD_WS.GetNewTransactionsRequest();
            inValue.Body = new Transactions_Automation.HAAD_WS.GetNewTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            return ((Transactions_Automation.HAAD_WS.WebservicesSoap)(this)).GetNewTransactionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Transactions_Automation.HAAD_WS.DownloadTransactionFileResponse Transactions_Automation.HAAD_WS.WebservicesSoap.DownloadTransactionFile(Transactions_Automation.HAAD_WS.DownloadTransactionFileRequest request) {
            return base.Channel.DownloadTransactionFile(request);
        }
        
        public int DownloadTransactionFile(string login, string pwd, string fileId, out string fileName, out byte[] file, out string errorMessage) {
            Transactions_Automation.HAAD_WS.DownloadTransactionFileRequest inValue = new Transactions_Automation.HAAD_WS.DownloadTransactionFileRequest();
            inValue.Body = new Transactions_Automation.HAAD_WS.DownloadTransactionFileRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.fileId = fileId;
            Transactions_Automation.HAAD_WS.DownloadTransactionFileResponse retVal = ((Transactions_Automation.HAAD_WS.WebservicesSoap)(this)).DownloadTransactionFile(inValue);
            fileName = retVal.Body.fileName;
            file = retVal.Body.file;
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.DownloadTransactionFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Transactions_Automation.HAAD_WS.DownloadTransactionFileResponse> Transactions_Automation.HAAD_WS.WebservicesSoap.DownloadTransactionFileAsync(Transactions_Automation.HAAD_WS.DownloadTransactionFileRequest request) {
            return base.Channel.DownloadTransactionFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<Transactions_Automation.HAAD_WS.DownloadTransactionFileResponse> DownloadTransactionFileAsync(string login, string pwd, string fileId) {
            Transactions_Automation.HAAD_WS.DownloadTransactionFileRequest inValue = new Transactions_Automation.HAAD_WS.DownloadTransactionFileRequest();
            inValue.Body = new Transactions_Automation.HAAD_WS.DownloadTransactionFileRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.fileId = fileId;
            return ((Transactions_Automation.HAAD_WS.WebservicesSoap)(this)).DownloadTransactionFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Transactions_Automation.HAAD_WS.SearchTransactionsResponse Transactions_Automation.HAAD_WS.WebservicesSoap.SearchTransactions(Transactions_Automation.HAAD_WS.SearchTransactionsRequest request) {
            return base.Channel.SearchTransactions(request);
        }
        
        public int SearchTransactions(string login, string pwd, int direction, string callerLicense, string ePartner, int transactionID, int transactionStatus, string transactionFileName, string transactionFromDate, string transactionToDate, int minRecordCount, int maxRecordCount, out string foundTransactions, out string errorMessage) {
            Transactions_Automation.HAAD_WS.SearchTransactionsRequest inValue = new Transactions_Automation.HAAD_WS.SearchTransactionsRequest();
            inValue.Body = new Transactions_Automation.HAAD_WS.SearchTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.direction = direction;
            inValue.Body.callerLicense = callerLicense;
            inValue.Body.ePartner = ePartner;
            inValue.Body.transactionID = transactionID;
            inValue.Body.transactionStatus = transactionStatus;
            inValue.Body.transactionFileName = transactionFileName;
            inValue.Body.transactionFromDate = transactionFromDate;
            inValue.Body.transactionToDate = transactionToDate;
            inValue.Body.minRecordCount = minRecordCount;
            inValue.Body.maxRecordCount = maxRecordCount;
            Transactions_Automation.HAAD_WS.SearchTransactionsResponse retVal = ((Transactions_Automation.HAAD_WS.WebservicesSoap)(this)).SearchTransactions(inValue);
            foundTransactions = retVal.Body.foundTransactions;
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.SearchTransactionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Transactions_Automation.HAAD_WS.SearchTransactionsResponse> Transactions_Automation.HAAD_WS.WebservicesSoap.SearchTransactionsAsync(Transactions_Automation.HAAD_WS.SearchTransactionsRequest request) {
            return base.Channel.SearchTransactionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Transactions_Automation.HAAD_WS.SearchTransactionsResponse> SearchTransactionsAsync(string login, string pwd, int direction, string callerLicense, string ePartner, int transactionID, int transactionStatus, string transactionFileName, string transactionFromDate, string transactionToDate, int minRecordCount, int maxRecordCount) {
            Transactions_Automation.HAAD_WS.SearchTransactionsRequest inValue = new Transactions_Automation.HAAD_WS.SearchTransactionsRequest();
            inValue.Body = new Transactions_Automation.HAAD_WS.SearchTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.direction = direction;
            inValue.Body.callerLicense = callerLicense;
            inValue.Body.ePartner = ePartner;
            inValue.Body.transactionID = transactionID;
            inValue.Body.transactionStatus = transactionStatus;
            inValue.Body.transactionFileName = transactionFileName;
            inValue.Body.transactionFromDate = transactionFromDate;
            inValue.Body.transactionToDate = transactionToDate;
            inValue.Body.minRecordCount = minRecordCount;
            inValue.Body.maxRecordCount = maxRecordCount;
            return ((Transactions_Automation.HAAD_WS.WebservicesSoap)(this)).SearchTransactionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Transactions_Automation.HAAD_WS.SetTransactionDownloadedResponse Transactions_Automation.HAAD_WS.WebservicesSoap.SetTransactionDownloaded(Transactions_Automation.HAAD_WS.SetTransactionDownloadedRequest request) {
            return base.Channel.SetTransactionDownloaded(request);
        }
        
        public int SetTransactionDownloaded(string login, string pwd, string fileId, out string errorMessage) {
            Transactions_Automation.HAAD_WS.SetTransactionDownloadedRequest inValue = new Transactions_Automation.HAAD_WS.SetTransactionDownloadedRequest();
            inValue.Body = new Transactions_Automation.HAAD_WS.SetTransactionDownloadedRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.fileId = fileId;
            Transactions_Automation.HAAD_WS.SetTransactionDownloadedResponse retVal = ((Transactions_Automation.HAAD_WS.WebservicesSoap)(this)).SetTransactionDownloaded(inValue);
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.SetTransactionDownloadedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Transactions_Automation.HAAD_WS.SetTransactionDownloadedResponse> Transactions_Automation.HAAD_WS.WebservicesSoap.SetTransactionDownloadedAsync(Transactions_Automation.HAAD_WS.SetTransactionDownloadedRequest request) {
            return base.Channel.SetTransactionDownloadedAsync(request);
        }
        
        public System.Threading.Tasks.Task<Transactions_Automation.HAAD_WS.SetTransactionDownloadedResponse> SetTransactionDownloadedAsync(string login, string pwd, string fileId) {
            Transactions_Automation.HAAD_WS.SetTransactionDownloadedRequest inValue = new Transactions_Automation.HAAD_WS.SetTransactionDownloadedRequest();
            inValue.Body = new Transactions_Automation.HAAD_WS.SetTransactionDownloadedRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.fileId = fileId;
            return ((Transactions_Automation.HAAD_WS.WebservicesSoap)(this)).SetTransactionDownloadedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Transactions_Automation.HAAD_WS.GetPrescriptionsResponse Transactions_Automation.HAAD_WS.WebservicesSoap.GetPrescriptions(Transactions_Automation.HAAD_WS.GetPrescriptionsRequest request) {
            return base.Channel.GetPrescriptions(request);
        }
        
        public int GetPrescriptions(string login, string pwd, string payerID, string memberID, out byte[] prescription, out string errorMessage) {
            Transactions_Automation.HAAD_WS.GetPrescriptionsRequest inValue = new Transactions_Automation.HAAD_WS.GetPrescriptionsRequest();
            inValue.Body = new Transactions_Automation.HAAD_WS.GetPrescriptionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.payerID = payerID;
            inValue.Body.memberID = memberID;
            Transactions_Automation.HAAD_WS.GetPrescriptionsResponse retVal = ((Transactions_Automation.HAAD_WS.WebservicesSoap)(this)).GetPrescriptions(inValue);
            prescription = retVal.Body.prescription;
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.GetPrescriptionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Transactions_Automation.HAAD_WS.GetPrescriptionsResponse> Transactions_Automation.HAAD_WS.WebservicesSoap.GetPrescriptionsAsync(Transactions_Automation.HAAD_WS.GetPrescriptionsRequest request) {
            return base.Channel.GetPrescriptionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Transactions_Automation.HAAD_WS.GetPrescriptionsResponse> GetPrescriptionsAsync(string login, string pwd, string payerID, string memberID) {
            Transactions_Automation.HAAD_WS.GetPrescriptionsRequest inValue = new Transactions_Automation.HAAD_WS.GetPrescriptionsRequest();
            inValue.Body = new Transactions_Automation.HAAD_WS.GetPrescriptionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.payerID = payerID;
            inValue.Body.memberID = memberID;
            return ((Transactions_Automation.HAAD_WS.WebservicesSoap)(this)).GetPrescriptionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Transactions_Automation.HAAD_WS.AddDRGToEClaimResponse Transactions_Automation.HAAD_WS.WebservicesSoap.AddDRGToEClaim(Transactions_Automation.HAAD_WS.AddDRGToEClaimRequest request) {
            return base.Channel.AddDRGToEClaim(request);
        }
        
        public int AddDRGToEClaim(string login, string pwd, byte[] originalFileContent, string originalFileName, decimal baseRate, out byte[] drgFileContent, out string drgFileName, out byte[] auditFileContent, out byte[] reportFileContent, out string errorMessage, out byte[] errorReport) {
            Transactions_Automation.HAAD_WS.AddDRGToEClaimRequest inValue = new Transactions_Automation.HAAD_WS.AddDRGToEClaimRequest();
            inValue.Body = new Transactions_Automation.HAAD_WS.AddDRGToEClaimRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.originalFileContent = originalFileContent;
            inValue.Body.originalFileName = originalFileName;
            inValue.Body.baseRate = baseRate;
            Transactions_Automation.HAAD_WS.AddDRGToEClaimResponse retVal = ((Transactions_Automation.HAAD_WS.WebservicesSoap)(this)).AddDRGToEClaim(inValue);
            drgFileContent = retVal.Body.drgFileContent;
            drgFileName = retVal.Body.drgFileName;
            auditFileContent = retVal.Body.auditFileContent;
            reportFileContent = retVal.Body.reportFileContent;
            errorMessage = retVal.Body.errorMessage;
            errorReport = retVal.Body.errorReport;
            return retVal.Body.AddDRGToEClaimResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Transactions_Automation.HAAD_WS.AddDRGToEClaimResponse> Transactions_Automation.HAAD_WS.WebservicesSoap.AddDRGToEClaimAsync(Transactions_Automation.HAAD_WS.AddDRGToEClaimRequest request) {
            return base.Channel.AddDRGToEClaimAsync(request);
        }
        
        public System.Threading.Tasks.Task<Transactions_Automation.HAAD_WS.AddDRGToEClaimResponse> AddDRGToEClaimAsync(string login, string pwd, byte[] originalFileContent, string originalFileName, decimal baseRate) {
            Transactions_Automation.HAAD_WS.AddDRGToEClaimRequest inValue = new Transactions_Automation.HAAD_WS.AddDRGToEClaimRequest();
            inValue.Body = new Transactions_Automation.HAAD_WS.AddDRGToEClaimRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.originalFileContent = originalFileContent;
            inValue.Body.originalFileName = originalFileName;
            inValue.Body.baseRate = baseRate;
            return ((Transactions_Automation.HAAD_WS.WebservicesSoap)(this)).AddDRGToEClaimAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Transactions_Automation.HAAD_WS.CheckForNewPriorAuthorizationTransactionsResponse Transactions_Automation.HAAD_WS.WebservicesSoap.CheckForNewPriorAuthorizationTransactions(Transactions_Automation.HAAD_WS.CheckForNewPriorAuthorizationTransactionsRequest request) {
            return base.Channel.CheckForNewPriorAuthorizationTransactions(request);
        }
        
        public int CheckForNewPriorAuthorizationTransactions(string login, string pwd, out string errorMessage) {
            Transactions_Automation.HAAD_WS.CheckForNewPriorAuthorizationTransactionsRequest inValue = new Transactions_Automation.HAAD_WS.CheckForNewPriorAuthorizationTransactionsRequest();
            inValue.Body = new Transactions_Automation.HAAD_WS.CheckForNewPriorAuthorizationTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            Transactions_Automation.HAAD_WS.CheckForNewPriorAuthorizationTransactionsResponse retVal = ((Transactions_Automation.HAAD_WS.WebservicesSoap)(this)).CheckForNewPriorAuthorizationTransactions(inValue);
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.CheckForNewPriorAuthorizationTransactionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Transactions_Automation.HAAD_WS.CheckForNewPriorAuthorizationTransactionsResponse> Transactions_Automation.HAAD_WS.WebservicesSoap.CheckForNewPriorAuthorizationTransactionsAsync(Transactions_Automation.HAAD_WS.CheckForNewPriorAuthorizationTransactionsRequest request) {
            return base.Channel.CheckForNewPriorAuthorizationTransactionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Transactions_Automation.HAAD_WS.CheckForNewPriorAuthorizationTransactionsResponse> CheckForNewPriorAuthorizationTransactionsAsync(string login, string pwd) {
            Transactions_Automation.HAAD_WS.CheckForNewPriorAuthorizationTransactionsRequest inValue = new Transactions_Automation.HAAD_WS.CheckForNewPriorAuthorizationTransactionsRequest();
            inValue.Body = new Transactions_Automation.HAAD_WS.CheckForNewPriorAuthorizationTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            return ((Transactions_Automation.HAAD_WS.WebservicesSoap)(this)).CheckForNewPriorAuthorizationTransactionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Transactions_Automation.HAAD_WS.GetNewPriorAuthorizationTransactionsResponse Transactions_Automation.HAAD_WS.WebservicesSoap.GetNewPriorAuthorizationTransactions(Transactions_Automation.HAAD_WS.GetNewPriorAuthorizationTransactionsRequest request) {
            return base.Channel.GetNewPriorAuthorizationTransactions(request);
        }
        
        public int GetNewPriorAuthorizationTransactions(string login, string pwd, out string foundTransactions, out string errorMessage) {
            Transactions_Automation.HAAD_WS.GetNewPriorAuthorizationTransactionsRequest inValue = new Transactions_Automation.HAAD_WS.GetNewPriorAuthorizationTransactionsRequest();
            inValue.Body = new Transactions_Automation.HAAD_WS.GetNewPriorAuthorizationTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            Transactions_Automation.HAAD_WS.GetNewPriorAuthorizationTransactionsResponse retVal = ((Transactions_Automation.HAAD_WS.WebservicesSoap)(this)).GetNewPriorAuthorizationTransactions(inValue);
            foundTransactions = retVal.Body.foundTransactions;
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.GetNewPriorAuthorizationTransactionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Transactions_Automation.HAAD_WS.GetNewPriorAuthorizationTransactionsResponse> Transactions_Automation.HAAD_WS.WebservicesSoap.GetNewPriorAuthorizationTransactionsAsync(Transactions_Automation.HAAD_WS.GetNewPriorAuthorizationTransactionsRequest request) {
            return base.Channel.GetNewPriorAuthorizationTransactionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Transactions_Automation.HAAD_WS.GetNewPriorAuthorizationTransactionsResponse> GetNewPriorAuthorizationTransactionsAsync(string login, string pwd) {
            Transactions_Automation.HAAD_WS.GetNewPriorAuthorizationTransactionsRequest inValue = new Transactions_Automation.HAAD_WS.GetNewPriorAuthorizationTransactionsRequest();
            inValue.Body = new Transactions_Automation.HAAD_WS.GetNewPriorAuthorizationTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            return ((Transactions_Automation.HAAD_WS.WebservicesSoap)(this)).GetNewPriorAuthorizationTransactionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Transactions_Automation.HAAD_WS.GetDRGDetailsResponse Transactions_Automation.HAAD_WS.WebservicesSoap.GetDRGDetails(Transactions_Automation.HAAD_WS.GetDRGDetailsRequest request) {
            return base.Channel.GetDRGDetails(request);
        }
        
        public int GetDRGDetails(string login, string pwd, string xmlClaimInput, out string xmlDRGDetails, out byte[] auditFileContent, out byte[] reportFileContent, out string errorMessage) {
            Transactions_Automation.HAAD_WS.GetDRGDetailsRequest inValue = new Transactions_Automation.HAAD_WS.GetDRGDetailsRequest();
            inValue.Body = new Transactions_Automation.HAAD_WS.GetDRGDetailsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.xmlClaimInput = xmlClaimInput;
            Transactions_Automation.HAAD_WS.GetDRGDetailsResponse retVal = ((Transactions_Automation.HAAD_WS.WebservicesSoap)(this)).GetDRGDetails(inValue);
            xmlDRGDetails = retVal.Body.xmlDRGDetails;
            auditFileContent = retVal.Body.auditFileContent;
            reportFileContent = retVal.Body.reportFileContent;
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.GetDRGDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Transactions_Automation.HAAD_WS.GetDRGDetailsResponse> Transactions_Automation.HAAD_WS.WebservicesSoap.GetDRGDetailsAsync(Transactions_Automation.HAAD_WS.GetDRGDetailsRequest request) {
            return base.Channel.GetDRGDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Transactions_Automation.HAAD_WS.GetDRGDetailsResponse> GetDRGDetailsAsync(string login, string pwd, string xmlClaimInput) {
            Transactions_Automation.HAAD_WS.GetDRGDetailsRequest inValue = new Transactions_Automation.HAAD_WS.GetDRGDetailsRequest();
            inValue.Body = new Transactions_Automation.HAAD_WS.GetDRGDetailsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.xmlClaimInput = xmlClaimInput;
            return ((Transactions_Automation.HAAD_WS.WebservicesSoap)(this)).GetDRGDetailsAsync(inValue);
        }
    }
}
